version: '3.8'

networks:
  moex_collector:
    driver: bridge

volumes:
  app-volume:

services:
  moex-spark:
    image: vielen1991/moex-spark:v6
    container_name: moex-spark
    hostname: moex-spark
    networks:
      - moex_collector
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_CASSANDRA_CONNECTION_HOST: cassandra
      SPARK_CASSANDRA_CONNECTION_PORT: 9042
      SPARK_JOB_CRON: "0 0 * * * *"
      JOB_PORT: 8000
    ports:
      - "8000:8000"

  moex-collector:
    image: vielen1991/moex-collector:v3
    container_name: moex-collector
    hostname: moex-collector
    networks:
      - moex_collector
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50M'
        reservations:
          cpus: '0.25'
          memory: '25M'
    environment:
      KAFKA_BROKER: kafka:29092
      POLL_INTERVAL: 1h
      BATCH_SIZE: 1000
      GOMEMLIMIT: '45MiB'
    volumes:
      - app-volume:/app

  moex-collector-rust:
    image: vielen1991/moex-collector-rust:v1
    container_name: moex-collector-rust
    hostname: moex-collector-rust
    networks:
      - moex_collector
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50M'
        reservations:
          cpus: '0.25'
          memory: '25M'
    environment:
      KAFKA_BROKER: kafka:29092
      POLL_INTERVAL: 2700
      BATCH_SIZE: 1000
    volumes:
      - app-volume:/app

  moex-streamlit:
    image: vielen1991/moex-streamlit:v1
    container_name: moex-streamlit
    hostname: moex-streamlit
    networks:
      - moex_collector
    environment:
      CASSANDRA_HOSTS: cassandra
      CASSANDRA_PORT: 9042
      KEYSPACE: moex
    ports:
      - "8501:8501"